server:
  port: 8083

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{correlationId:-}]"

spring:
  application:
    name: payment-service
  config:
    import: optional:classpath:tracing-common.yml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
